
;; additional game-specific subroutines go here

.include "game/subroutine/AddAccumulatorToScore.asm"
.include "game/subroutine/BackgroundNoise.asm"
.include "game/subroutine/BlindsEffect.asm"
.include "game/subroutine/ClearScreen.asm"
.include "game/subroutine/ColorizeBall.asm"
.include "game/subroutine/ColorsMatch.asm"
.include "game/subroutine/ConvertXYToTileType.asm"
.include "game/subroutine/DisableEnableRendering.asm"
.include "game/subroutine/DrawIntroScreenLogoTile.asm"
.include "game/subroutine/DrawMoveTile.asm"
.include "game/subroutine/DrawTileTemp018.asm"
.include "game/subroutine/EvaluateTileType.asm"
.include "game/subroutine/FlashEffect.asm"
.include "game/subroutine/GetPPUAddrFromYXIndex.asm"
.include "game/subroutine/InitiateNudge.asm"
.include "game/subroutine/JumpToPointer.asm"
.include "game/subroutine/LoadAnimations.asm"
.include "game/subroutine/LoadGameScreen.asm"
.include "game/subroutine/LoadIntroScreen.asm"
.include "game/subroutine/LoadWinScreen.asm"
.include "game/subroutine/PreloadSfxFromX.asm"
.include "game/subroutine/RemoveBlockFromScreen.asm"
.include "game/subroutine/SetTileAttributeAddress.asm"
.include "game/subroutine/SubtractXFromBonus.asm"
.include "game/subroutine/WaitXFrames.asm"
.include "game/subroutine/Waste.asm"
.include "game/subroutine/WriteByteToPPUBuffer.asm"

